#!/usr/bin/env bash

#Install vim-plug for Vim and install the Plugins
echo "Installling vim-plug for Vim and Plugins..."
if [[ ! -e "$HOME/.vim/autoload/plug.vim" ]]; then 
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && vim -E -u "$HOME/.vimrc" +PlugInstall +qall
else
    vim -E -u "$HOME/.vimrc" +PlugInstall +qall
fi    
echo "vim-plug and Plugins installation complete"
